---
title: '[Week 02] Simulation Evaluation'
author: Giuliano Sposito
date: '2020-09-22'
slug: week02_eval
categories:
  - evaluation
tags:
  - evaluation
  - simulation
description: ''
dropCap: yes
displayInMenu: no
displayInList: no
resources:
- name: featuredImage
  src: "wargames_norad.jpeg"
  params:
    description: War Games Wopr
params:
  week: 2
  version: 5
  prefix: posSNF
---

**Matchup Winner Accuracy: 60%**

<!--more-->

## Historic

| week | Winner Accuracy |
|:----:|:---------------:|
| 14   |       ??%       |


```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
# put rnotbook in the same workdir
knitr::opts_knit$set(root.dir = normalizePath(rprojroot::find_rstudio_root_file())) 
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r loadAndDataHandling}
# libs
library(tidyverse)
library(glue)
library(ggimage)
library(knitr)
library(kableExtra)

# PARAMETERS
.week <- params$week
.version <- params$version
.prefix <- params$prefix

# SIMULATION

sim <- readRDS(glue("./data/simulation_v{.version}_week{.week}_posSNF.rds"))

sim$matchup_sim %>% 
  select(awayTeam.teamId, awayTeam.totalPts, homeTeam.teamId, homeTeam.totalPts, homeTeam.ptsdiff.org) %>% 
  mutate( prediction.scoreDiff = map_dbl(homeTeam.ptsdiff.org,mean),
          prediction.id = if_else(prediction.scoreDiff>0,homeTeam.teamId, awayTeam.teamId),
          who.won       = if_else(homeTeam.totalPts>awayTeam.totalPts, homeTeam.teamId, awayTeam.teamId) )

sim_summary <- bind_rows(
    select(sim$matchup_sim, teamId=awayTeam.teamId, winProb=awayTeam.winProb, sim.pts=awayTeam.simulation),
    select(sim$matchup_sim, teamId=homeTeam.teamId, winProb=homeTeam.winProb, sim.pts=homeTeam.simulation)
  ) %>% inner_join(select(sim$teams, -rosters), by="teamId")

```
