---
title: '[Week 10] Players Projection and Matchups Simulation'
author: 'Giuliano Sposito'
date: '2019-11-07'
categories:
  - projection
  - simulation
tags:
  - projection
  - simulation
slug: week10
dropCap: no
displayInMenu: no
displayInList: yes
resources:
- name: featuredImage
  src: "Jackson.jpg"
  params:
    description: "Lamar Jackson"
params:
  week: 10
---

*Last Update: Pre Waivers*

<!--more-->

## Game Center

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
# put rnotbook in the same workdir
knitr::opts_knit$set(root.dir = normalizePath(rprojroot::find_rstudio_root_file())) 
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r gameCenterChart, fig.height=4, fig.width=8}
library(tidyverse)
library(glue)

sim <- readRDS("./data/simulations_history.rds") %>% 
  filter(week==params$week) %>%
  filter(timestamp==max(timestamp, na.rm=T)) %>%
  unnest(home.points, away.points, .sep = ".")
  

lastUpdate <- unique(sim$timestamp) 
lastPrefix <- unique(sim$prefix)

sim %>% 
  select(week, timestamp, prefix, 
         contains("logoUrl"),
         contains("name"),
         contains("record"),
         contains("win.prob"),
         contains("pts"),
         contains("Median"),
         contains("minutesRemaining")) %>% 
  mutate( game.id = glue("({away.minutesRemaining} min) {away.name} @ {home.name} ({home.minutesRemaining} min)") ) %>%
  ggplot(aes(x=0)) +
  geom_col(aes(y=home.points.Median), fill="lightgray", width = .7) +
  geom_col(aes(y=home.pts), fill="darkred", width = .5) +
  geom_col(aes(y=-away.points.Median), fill="lightgray", width = .7) +
  geom_col(aes(y=-away.pts), fill="darkblue", width = .5) +
  geom_text(aes(y=home.points.Median, label=round(home.points.Median,2)), size=4,
            hjust = "left", vjust="middle", color="black", nudge_y = 2, nudge_x = .05) +
  geom_text(aes(y=home.pts, label=round(home.pts,2)), size=4,
            hjust = "right", vjust="middle", color="white", nudge_y = -2, nudge_x = .05) +
  geom_text(aes(y=-away.points.Median, label=round(away.points.Median,2)), size=4,
            hjust = "right", vjust="middle", color="black", nudge_y = -2, nudge_x = .05) +
  geom_text(aes(y=-away.pts, label=round(away.pts,2)), size=4,
            hjust = "left", vjust="middle", color="white", nudge_y = 2, nudge_x = .05) +
  coord_flip() +
  facet_wrap(~game.id, ncol = 1) +
  labs(x="", title=glue("Last Update: {lastUpdate} - {lastPrefix}"),
       subtitle = "") +
  xlim(-.5,.5) +
  ylim(-1.1*max(sim$away.points.Median), 1.1*max(sim$home.points.Median)) +
  theme_void() +
  theme( strip.text = element_text(size=12, face = "bold"), 
         plot.margin = unit(c(15,15,15,15),"pt"),
         plot.title = element_text(hjust = .5, size=10),
         plot.subtitle = element_text(hjust = .5))

```


## Projections

- [Individual Players Projections](/reports/ffa_players_projection_week10.html)

## Simulations

- [Pre Waivers](/reports/dudes_simulation_week10_preWaivers_v3.html)

## Twittersphere

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">GOATden Tate forever <a href="https://t.co/HU99K12vnP">pic.twitter.com/HU99K12vnP</a></p>&mdash; new-age analytical (@benbbaldwin) <a href="https://twitter.com/benbbaldwin/status/1191536010208960513?ref_src=twsrc%5Etfw">November 5, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


