---
title: '[Week 04] Projections and Simulation'
author: Giuliano Sposito
date: '2020-09-30'
slug: week-04-projections-and-simulation
categories:
  - projection
  - simulation
tags:
  - montecarlo
  - projection
  - simulation
dropCap: no
displayInMenu: no
displayInList: yes
resources:
- name: featuredImage
  params:
    description: Atlanta at Dallas
  src: Ravens_vs_Chiefs_2019_chiefs_1.jpg
params:
  week: 4
  prefix: "posWaiver"
---

_Last Update: `r lubridate::now()`_

<!--more-->

## Game Center

```{r setup, include=FALSE}

# put rnotbook in the same workdir
knitr::opts_knit$set(root.dir = normalizePath(rprojroot::find_rstudio_root_file())) 
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

```{r gamecenter, fig.width=6, fig.height=4}
library(tidyverse)
library(glue)

.week <- params$week
.prefix <- params$prefix

sim <- readRDS(glue("./data/simulation_v5_week{.week}_{.prefix}.rds"))

# game summary in long form
sim_summary <- bind_rows(
  select(sim$matchup_sim, teamId=awayTeam.teamId, winProb=awayTeam.winProb, sim.pts=awayTeam.simulation),
  select(sim$matchup_sim, teamId=homeTeam.teamId, winProb=homeTeam.winProb, sim.pts=homeTeam.simulation)
) %>% inner_join(select(sim$teams, -rosters), by="teamId")

# obtem nome e pontuacao dos times
team_points <- sim$teams %>% 
  unnest(week.stats) %>% 
  filter(week==.week) %>% 
  select(teamId, name, pts, imageUrl)

games_summary <- sim$matchup_sim %>% 
  inner_join(set_names(team_points, paste0("away.",names(team_points))), by=c("awayTeam.teamId"="away.teamId")) %>% 
  inner_join(set_names(team_points, paste0("home.",names(team_points))), by=c("homeTeam.teamId"="home.teamId")) %>% 
  mutate(game=paste0(away.name, " @ ", home.name)) %>%
  select(game, homeTeam.ptsdiff, homeTeam.ptsdiff.org, home.pts, away.pts,
         home.teamId=homeTeam.teamId, away.teamId=awayTeam.teamId,
         home.name,away.name, home.projPts=homeTeam.totalPts, away.projPts = awayTeam.totalPts) %>% 
  mutate( away.nickname = gsub("([a-zA-Z\']+ )?", "", away.name),
          home.nickname = gsub("([a-zA-Z\']+ )?", "", home.name)) %>% 
  mutate( game.nickname = paste0(away.nickname, " @ ", home.nickname))

team_prob <- sim_summary %>%
  select(teamId, teamName=name, winProb, imageUrl)

team_rem <- sim$teams %>% 
  select(teamId, rosters, season.stats) %>% 
  unnest(c(rosters, season.stats)) %>% 
  filter(rosterSlotId < 20) %>% 
  group_by(teamId, record) %>% 
  summarise(teamRemaining=sum(isEditable), .groups="keep") %>% 
  ungroup() %>% 
  mutate(record = str_remove(record, "-0")) %>% 
  select(teamId, record, teamRemaining) %>% 
  inner_join(team_prob, by="teamId")

game_center <- games_summary %>% 
  select(game.nickname, away.nickname, away.projPts, away.pts, away.teamId, away.name,
         home.pts, home.projPts, home.nickname, home.teamId, home.name) %>% 
  left_join(set_names(team_rem, paste0("home.",names(team_rem))), by = "home.teamId") %>% 
  left_join(set_names(team_rem, paste0("away.",names(team_rem))), by = "away.teamId")
```


## Projections

- [Individual Players Projections](/reports/2020/ffa_players_projection_week4.html)

## Simulation

- [Matchup Simulations Pos-Waiver](/reports/2020/dudes_simulation_v5_week4_posWaiver.html)
- [Matchup Simulations Pre-Waiver](/reports/2020/dudes_simulation_v5_week4_preWaiver.html)