---
title: "Dudes Football League - Simulation"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
params:
  week: 1
  prefix: "posTNF"
---

```{r setup, include=FALSE}

# put rnotbook in the same workdir
knitr::opts_knit$set(root.dir = normalizePath(rprojroot::find_rstudio_root_file())) 
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```


```{r libs}
library(flexdashboard)
library(tidyverse)
#library(formattable)
library(ggrepel)
library(glue)
library(broom)

.week <- params$week
.prefix <- params$prefix

# fixed positions for charts
slotLevels <- gl(8,1,labels=c("QB","RB","WR","TE","W/R","K","DEF","BN", "RES", "??"))
posLevels <- gl(6,1,labels=c("QB","RB","WR","TE","K","DEF"))

# map to roster position
rosterSlots <- tibble(
  rosterSlotId = c(1:5,7,8,20,21),
  rosterSlot   = c("QB","RB","WR","TE","W/R","K","DEF","BN","RES")
)

# recover simulation data
sim <- readRDS(glue("./data/simulation_v5_week{.week}_{.prefix}.rds")) 

# sim.summary <- tibble(
#   team.id   = c(sim$home.id,   sim$away.id),
#   team.name = c(sim$home.name,     sim$away.name),
#   pts.summ  = c(sim$home.points,   sim$away.points),
#   points    = c(sim$home.sim,      sim$away.sim),
#   win.pc    = c(sim$home.win.prob, sim$away.win.prob),
#   roster    = c(sim$home.roster, sim$away.roster)
# ) 

# game summary in long form
sim_summary <- bind_rows(
    select(sim$matchup_sim, teamId=awayTeam.teamId, winProb=awayTeam.winProb, sim.pts=awayTeam.simulation),
    select(sim$matchup_sim, teamId=homeTeam.teamId, winProb=homeTeam.winProb, sim.pts=homeTeam.simulation)
  ) %>% inner_join(select(sim$teams, -rosters), by="teamId")

# obtem nome e pontuacao dos times
team_points <- sim$teams %>% 
  unnest(week.stats) %>% 
  filter(week==.week) %>% 
  select(teamId, name, pts)

games_summary <- sim$matchup_sim %>% 
  inner_join(set_names(team_points, paste0("away.",names(team_points))), by=c("awayTeam.teamId"="away.teamId")) %>% 
  inner_join(set_names(team_points, paste0("home.",names(team_points))), by=c("homeTeam.teamId"="home.teamId")) %>% 
  mutate(game=paste0(away.name, " @ ", home.name)) %>%
  select(game, homeTeam.ptsdiff, homeTeam.ptsdiff.org, home.pts, away.pts,
         home.teamId=homeTeam.teamId, away.teamId=awayTeam.teamId,
         home.name,away.name) %>% 
  mutate( away.nickname = gsub("([a-zA-Z\']+ )?", "", away.name),
          home.nickname = gsub("([a-zA-Z\']+ )?", "", home.name)) %>% 
  mutate( game.nickname = paste0(away.nickname, " @ ", home.nickname))

# code to plot a gauge
winGauge <- function(.teamId, .teamSummary) {
  values <- .teamSummary %>%
    filter(teamId == .teamId) %>%
    mutate( winProb = round(100*winProb) ) %>%
    select(name, winProb)
  
  gauge(value=values$winProb, min = 0, max = 100, symbol = '%', label = values$name,
          gaugeSectors(success = c(61, 100), warning = c(40, 60), danger = c(0, 39)))
}

```

Win Probability {data-navmenu="Overview"}
=======================

Row
-------------------------------------

### `r games_summary[1,]$game.nickname`
```{r}
winGauge(games_summary[1,]$away.teamId,sim_summary)
winGauge(games_summary[1,]$home.teamId,sim_summary)
```

### `r games_summary[2,]$game.nickname`
```{r}
winGauge(games_summary[2,]$away.teamId,sim_summary)
winGauge(games_summary[2,]$home.teamId,sim_summary)
```

Row
-------------------------------------

### `r games_summary[3,]$game.nickname`
```{r}
winGauge(games_summary[3,]$away.teamId,sim_summary)
winGauge(games_summary[3,]$home.teamId,sim_summary)
```

### `r games_summary[4,]$game.nickname`
```{r}
winGauge(games_summary[4,]$away.teamId,sim_summary)
winGauge(games_summary[4,]$home.teamId,sim_summary)
```

Row
-------------------------------------

### `r games_summary[5,]$game.nickname`
```{r}
winGauge(games_summary[5,]$away.teamId,sim_summary)
winGauge(games_summary[5,]$home.teamId,sim_summary)
```

### `r games_summary[6,]$game.nickname`
```{r}
winGauge(games_summary[6,]$away.teamId,sim_summary)
winGauge(games_summary[6,]$home.teamId,sim_summary)
```

Row
-------------------------------------

### `r games_summary[7,]$game.nickname`
```{r}
winGauge(games_summary[7,]$away.teamId,sim_summary)
winGauge(games_summary[7,]$home.teamId,sim_summary)
```


Points Distribution {data-navmenu="Overview"}
=======================================

```{r teamPtsDist, fig.width=9}

sim_summary %>% 
  select(name, sim.pts) %>% 
  mutate(mean.pts = map_dbl(sim.pts, mean)) %>% 
  unnest(sim.pts) %>% 
  mutate(sim.pts = round(sim.pts,1)) %>%
  ggplot(aes(x=reorder(name,mean.pts), y=sim.pts, color=name)) +
  geom_boxplot() +
  coord_flip() +
  theme_minimal() +
  ggtitle("Simulated Points Distribution") +
  xlab( "fantasy team" ) +
  ylab( "simulation points" ) +
  theme( legend.position = "none" )

```

Score Difference {data-navmenu="Overview"}
============================================

```{r matchupScoreDiffDist, fig.width=9}
games_summary %>%
  mutate(current.score.diff = home.pts-away.pts) %>% 
  unnest(c(homeTeam.ptsdiff, homeTeam.ptsdiff.org)) %>% 
  ggplot(aes(fill=game)) +
  geom_density(aes(homeTeam.ptsdiff.org), fill="grey", color=NA, alpha=.4) +
  geom_density(aes(homeTeam.ptsdiff), alpha=.6) +
  geom_vline(aes(xintercept=0), linetype=1, color="black", alpha=.5) +
  geom_vline(aes(xintercept=current.score.diff),
             linetype=2, color="red") +
  facet_grid(rows=vars(game), switch = "x", scales="free") +
  theme_minimal() +
  ggtitle("Matchups Score Difference") +
  ylab("Probability Distribution") +
  xlab("Score Difference") +
  theme( legend.position = "none", strip.text.y = element_text(angle=0) )

```

```{r rosterComparation}

## preparacao dos dados dos rosters

# seleciona algumas colunas ta tabela de projecao
projections <- sim$proj_table %>% 
  filter(position==pos) %>% 
  select(id, projPts = points, pos_rank, drop_off, sd_pts, floor, ceiling, tier) 

# junta os rosters dos times, estatíticas dos jogadores, a tabela de projecao e
# uma de-para de apreviacao do Injury Status
rosters <- sim$teams %>% 
  # unnest do roster por time
  select(teamId, teamName=name, rosters) %>% 
  unnest(rosters) %>%                                                         # 210 players
  # mapeamento ffa<->nfl
  inner_join(select(sim$players_id, id, playerId=nfl_id), by="playerId") %>%  # 210 players
  # statisticas dos jogadores
  inner_join(sim$players_stats, by="playerId") %>%                            # 210 players]
  # estatisticas podem ter mais de uma semana
  unnest(weekPts) %>% 
  filter(week == .week) %>% 
  # mapeamento da posicao do slot no roster
  left_join(rosterSlots, by="rosterSlotId") %>% 
  # campos de interesse
  select(id, playerId, teamId, teamName, name, position, nflTeamAbbr, rosterSlot, 
         injuryGameStatus, isEditable, isReserveStatus=isReserveStatus.x, isUndroppable, 
         byeWeek, weekPts, seasonPts) %>% 
  # adiciona as projecoes
  left_join(projections, by="id") %>% 
  # adiciona abreviatura do injury game status
  left_join(readRDS("./data/injuryGameStatusAbbr.rds"), by = "injuryGameStatus")
  # %>% replace_na(list(points=0, floor=0, ceiling=0))

## plot do grafico do roster
plotRoster <- function(.teamId, .rosterData) {
  
  .rosterData %>% 
    filter(teamId==.teamId) %>% 
    mutate(
      # fixa posicao e slot como fatores fixo para melhorar o gráfico
      position = factor(position, levels=posLevels),
      rosterSlot = factor(rosterSlot, levels=slotLevels)
    ) %>% 
    # decide se em pontos deixa vazio (ainda nao jogou) ou coloca week points (já jogou)
    mutate(
      points = case_when(
        isEditable ~ as.numeric(NA),
        !isEditable ~ weekPts 
      )
    ) %>% 
    # modifica o label do jogador conforme for o status de lesao
    mutate(
      playerLabel = case_when(
        !is.na(injuryGameStatus) ~ paste0(name, " (",injuryAbbr, ")" ," [", rosterSlot,"]"),
        T ~ paste0(name," [", rosterSlot,"]")
      )
    ) %>% 
    arrange(rosterSlot, position) %>% 
    mutate(display.order=1:nrow(.)) %>% 
    ggplot(aes(x=reorder(playerLabel, -display.order), color=position)) +
    geom_pointrange(aes(y=projPts, ymin=floor, ymax=ceiling)) +
    geom_label(aes(y=projPts, label=round(projPts,1)), size = 3,
               label.padding = unit(0.15, "lines"), show.legend = F) +
    geom_point(aes(y=points), size=2, color="black") +
    xlab("") +
    ylab("Fantasy Points") +
    coord_flip() +
    theme_minimal() +
    theme(legend.position = "bottom")  
}

```

```{r rosterComparationMenu, results='asis'}

for(i in 1:nrow(games_summary)){
  matchup <- games_summary[i,]

  cat(paste0("\n",matchup$game.nickname," {data-navmenu=\"Roster Comparation\"  data-orientation=columns}\n"))
  cat("============================================\n")
  
  cat("\nColumn\n--------------------------------------------\n")
  cat(paste0("\n### ", matchup$away.name), "\n\n")
  print(plotRoster(matchup$away.teamId, rosters))
  cat("\n")
  
  cat("\nColumn\n--------------------------------------------\n")
  cat(paste0("\n### ", matchup$home.name), "\n\n")
  print(plotRoster(matchup$home.teamId, rosters))
  cat("\n")
}

```