---
title: "It's Football, dudes - Fantasy League"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
params:
  week: 0
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(glue)
library(ggrepel)

week <- params$week

```

```{r loaddata, cache=FALSE}

# pega projecoes cria algumas colunas auxiliares
projections <- readRDS(glue("../../data/week{week}_players_projections.rds")) %>% 
  mutate( full_name = paste0(first_name, " ", last_name),
          fantasy.team = as.factor(fantasy.team) ) %>%
  group_by( id ) %>% 
  mutate( r_pos = max(ceiling, points) ) %>% # posicao do label
  ungroup() %>% 
  filter( !(team %in% c("FA","FA*")) ) # havia lixo em alguns


readRDS("../../data/players_points.rds") %>%
  filter( points!=0 ) %>% 
  rename( pts = points ) %>% 
  select( id, week, pts) %>% 
  group_by( id ) %>% 
  mutate( pts.mean = median(pts, na.rm = T),
          pts.sd   = sd(pts, na.rm=T),
          pts.max = max(pts, na.rm=T),
          pts.min = min(pts, na.rm = T)) %>% 
  ungroup() %>% 
  right_join(projections, by = "id") -> projections
  
```

QB {data-navmenu="ffanalytics"}
========================

```{r qb, fig.width=10}

plotProjections <- function(.proj, .pos, .title, .subtitle, .slice=32) {
  require(magrittr)
  proj_data <- .proj %>% 
    select(id, position, pos_rank ) %>% 
    filter(position==.pos) %>% 
    distinct() %>% 
    top_n(-.slice, pos_rank) %>% 
    select(id)
  
  proj_data %>% 
    inner_join(.proj, by="id") -> proj_data
  
  nu_y <- max(proj_data$ceiling, na.rm = T) / 18
  
  proj_data %>% 
    ggplot(aes(group=fantasy.team)) +
    geom_pointrange(aes(x=reorder(pos_rank,desc(pos_rank)),
                    y=points, 
                    ymin=floor, 
                    ymax=ceiling, 
                    color=fantasy.team), size=1) +
    # geom_point(aes(x=reorder(pos_rank,desc(pos_rank)),
    #                y=pts), color="black", alpha=.05) +
    geom_point(aes(x=reorder(pos_rank,desc(pos_rank)),
                   y = pts.mean), color="black", alpha=.5) +
    # geom_pointrange(aes(x=reorder(pos_rank,desc(pos_rank)),
    #                     y=pts.mean,
    #                     ymin=pts.mean-pts.sd,
    #                     ymax=pts.mean+pts.sd),
    #                 color="grey",
    #                 size=.5,
    #                 alpha=.5) +
    geom_text(aes(x=reorder(pos_rank,desc(pos_rank)), 
              y=r_pos, 
              color=fantasy.team, 
              label=full_name), nudge_y = nu_y, nudge_x = 0.0, size=3) +
    scale_colour_manual(values = c("grey",  "#e31a1c", "#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#fdbf6f", "#ff7f00")) +
    theme_classic() + xlab("Rank") + ylab("Points") +
    theme( panel.grid.major.x=element_line(colour="#EEEEEE") ) +
    scale_x_discrete(breaks = seq(1,32,4) ) +
    ggtitle(.title,.subtitle) +
    coord_flip() -> g
  
  g %>% 
    ggplotly() %>% 
    return()
  
}

plotProjections(projections, "QB", "Quaterbacks", "week 9", 20)

```

WR {data-navmenu="ffanalytics"}
========================

```{r wr, fig.width=10}

plotProjections(projections, "WR", "Wide Receivers", "week 9",50)

```

RB {data-navmenu="ffanalytics"}
========================

```{r rb, fig.width=10}

plotProjections(projections, "RB", "Running Backs", "week 9",50)

```

TE {data-navmenu="ffanalytics"}
========================

```{r te, fig.width=10}

plotProjections(projections, "TE", "Tight Ends", "week 9",20)

```


K {data-navmenu="ffanalytics"}
========================

```{r k, fig.width=10}

plotProjections(projections, "K", "Kickers", "week 9",20)

```


DEF {data-navmenu="ffanalytics"}
========================

```{r def, fig.width=10}

plotProjections(projections, "DST", "Defenses", "week 9",32)

```


```{r historicData}

p.stats <- readRDS("../../data/players_points.rds") %>% 
  mutate( points = case_when(
    points==0 & position=="DST" ~ points,
    points==0 & position!="DST" ~ as.numeric(NA),
    points!=0 ~ points
  ))

p.projs <- readRDS(glue("../../data/week{week}_players_projections.rds")) %>% 
  mutate( full_name = paste0(first_name, " ", last_name) ) %>% 
  select(id, fantasy.team, full_name, team, position, avg_type, pos_rank, proj.points=points) %>% 
  filter( avg_type == "weighted" )

p.stats %>% 
  group_by(id) %>% 
  summarise(
    mean = mean(points, na.rm = T),
    sd   = sd(points, na.rm = T)
  ) %>% 
  inner_join(p.projs,by="id") -> sharpe.data

plotSharpe <- function(.dtfm, .pos, .n) {
  .dtfm %>% 
    filter( position==.pos ) %>% 
    top_n(-.n, pos_rank ) %>% 
    mutate( mean=round(mean,1), sd=round(sd,1) ) %>% 
    ggplot(aes(x=sd, y=mean, color=fantasy.team)) +
    geom_point() +
    geom_text_repel(aes(label=full_name), show.legend = F, size=3, point.padding = .5) +
    geom_label( aes(label=mean), size = 3, label.padding = unit(0.15, "lines"), show.legend = F) +
    theme_minimal() +
    ggtitle(.pos) + xlab("variance") + ylab("mean points")  
}

```


QB {data-navmenu="record"}
========================
```{r histQB, fig.width=10}
plotSharpe(sharpe.data, "QB",8*3)
```


WR {data-navmenu="record"}
========================
```{r histWR, fig.width=10}
plotSharpe(sharpe.data, "WR", 8*5)
```


RB {data-navmenu="record"}
========================
```{r histRB, fig.width=10}
plotSharpe(sharpe.data, "RB", 8*5)
```


TE {data-navmenu="record"}
========================
```{r histTE, fig.width=10}
plotSharpe(sharpe.data, "TE", 3*8)
```


K {data-navmenu="record"}
========================
```{r histK, fig.width=10}
plotSharpe(sharpe.data, "K", 3*8)
```

DEF {data-navmenu="record"}
========================
```{r histDEF, fig.width=10}
plotSharpe(sharpe.data, "DST", 3*8)
```

